@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package mod.legacyprojects.nostalgic.client.gui.widget.keybinding;

import mod.legacyprojects.nostalgic.annotation.MethodsReturnNonnullByDefault;
import mod.legacyprojects.nostalgic.annotation.ParametersAreNonnullByDefault;