@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package mod.legacyprojects.nostalgic.client.gui.screen.vanilla.world;

import mod.legacyprojects.nostalgic.annotation.MethodsReturnNonnullByDefault;
import mod.legacyprojects.nostalgic.annotation.ParametersAreNonnullByDefault;