@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package mod.legacyprojects.nostalgic.mixin.sodium;

import mod.legacyprojects.nostalgic.annotation.MethodsReturnNonnullByDefault;
import mod.legacyprojects.nostalgic.annotation.ParametersAreNonnullByDefault;